name: RSS to MD
on:
  schedule:
    - cron: "0 * * * *"     # Runs every hour
  workflow_dispatch:
jobs:
  rss2md:
    name:  RSS to MD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # wenchiehlee@investment
      - uses: sarisia/actions-readme-feed@v1
        id: _feedinvestment1_
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 500
          sort: true
          format: '- ${monthshort} ${02day} - [${title}](${url})' 
          start_flag: "<!-- _feedinvestment1_ start -->"
          end_flag: "<!-- _feedinvestment1_ end -->"
          url: |
            https://www.google.com.tw/alerts/feeds/12063940936216578696/18175540292638798833
      - uses: sarisia/actions-readme-feed@v1
        id: _feedinvestment2_
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 500
          sort: true
          format: '- ${monthshort} ${02day} - [${title}](${url})' 
          start_flag: "<!-- _feedinvestment2_ start -->"
          end_flag: "<!-- _feedinvestment2_ end -->"
          url: |
            https://www.google.com/alerts/feeds/12063940936216578696/11229675591975377803
      # wenchiehlee@work  
      - uses: sarisia/actions-readme-feed@v1
        id: _feedwork_
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 500
          sort: true
          format: '- ${04year}/${02month}/${02day} - [${title}](${url})' 
          start_flag: "<!-- _feedwork_ start -->"
          end_flag: "<!-- _feedwork_ end -->"
          url: |
            https://wenchiehlee.github.io/mkdocs/feed_rss_created.xml
      # wenchiehlee@life 
      - uses: sarisia/actions-readme-feed@v1
        id: _feedlife_
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 500
          sort: true
          format: '- ${04year}/${02month}/${02day} - [${title}](${url})' 
          start_flag: "<!-- _feedlife_ start -->"
          end_flag: "<!-- _feedlife_ end -->"
          url: |
            https://wenchiehlee.wordpress.com/feed
            https://wenflower.blogspot.com/feeds/posts/default
            https://wenbike.blogspot.com/feeds/posts/default
            https://medium.com/feed/@wenchiehlee1020
            https://feeds.feedburner.com/blogspot/bREW
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: verify README
      #    path: README.md
      #    if: always()
      - if: ${{ steps._feed_.outputs.changed}} == 'true'|| ${{steps._feedwork_.outputs.changed}} == 'true' || ${{steps._feedlife_.outputs.changed}} 
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
