name: RSS to MD
on:
  schedule:
    - cron: "0 * * * *"     # Runs every hour
  workflow_dispatch:
jobs:
  rss2md:
    name:  RSS to MD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sarisia/actions-readme-feed@v1
        id: _feed_
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 500
          sort: true
          format: '- ${monthshort} ${02day} - [${title}](${url})' 
          start_flag: "<!-- rss start -->"
          end_flag: "<!-- rss end -->"
          url: |
            https://www.google.com/alerts/feeds/12063940936216578696/8793798168837785642
            https://www.google.com/alerts/feeds/12063940936216578696/8793798168837786674
      # wenchiehlee@work  
      - uses: sarisia/actions-readme-feed@v1
        id: _feed1_
        with:
          file: 'README.md'
          timezone: 'Asia/taipei'
          max_entry: 500
          sort: true
          format: '- ${04year} {02month} ${02day} - [${title}](${url})' 
          start_flag: "<!-- _feed1_ start -->"
          end_flag: "<!-- _feed1_ end -->"
          url: |
            https://wenchiehlee.github.io/mkdocs/feed_rss_created.xml
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: verify README
      #    path: README.md
      #    if: always()
      - run: echo ${{steps._feed_.outputs.changed}}
      - run: echo ${{steps._feed1_.outputs.changed}}
      - if: ${{ steps._feed_.outputs.changed}} == 'true'|| ${{steps._feed1_.outputs.changed}} == 'true'
        uses: sarisia/actions-commit@master
